brigade-github-app:
  enabled: true
  service:
    type: NodePort
  ingress:
    hosts:
      - brigade-github-app.evkube.evdev.me
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
    - hosts:
      - brigade-github-app.evkube.evdev.me
      secretName: brigade-github-app-tls
  github:
    appID: 36087
worker:
  defaultBuildStorageClass: nfs
  defaultCacheStorageClass: nfs